In [253]:
from requests_html import HTMLSession
import csv
import json

In [202]:
session = HTMLSession()
r = session.get(f'https://api.digikala.com/v1/categories/mouse/search/?sort=7&seo_url=%2Fcategory-mouse%2F%3Fsort%3D7&page=1')
data_json = json.loads(r.text)


for i in range(20):
    kala = data_json["data"]["products"][i]
    id = kala["id"]

In [186]:
# import json
comment = session.get(f'https://api.digikala.com/v1/product/2542095/comments/')
comment = json.loads(comment.text)
print(comment["data"]["pager"]["total_items"])

249

In [187]:
question = session.get(f'https://api.digikala.com/v1/product/2542095/questions/')
question = json.loads(question.text)
question["data"]["pager"]["total_items"]

205

In [220]:
with open('export.csv', 'w' ,encoding="utf-8") as f:
    write = csv.writer(f)
    
    for pagenumber in range(1,10):
        r = session.get(f'https://api.digikala.com/v1/categories/mouse/search/?sort=7&seo_url=%2Fcategory-mouse%2F%3Fsort%3D7&page={pagenumber}')
        data_json = json.loads(r.text)
    
        for i in range(20):
            kala = data_json["data"]["products"][i]
            id = kala["id"]
    
            name = kala["title_fa"]
            all_star = kala["data_layer"]["metric6"]
            star_rate = kala["data_layer"]["dimension9"]
            price     = kala["default_variant"]["price"]["selling_price"]


            #################### feeling good rating
            try:
                total_count = kala["default_variant"]["statistics"]["total_count"]
            except:
                total_count = None
            try:
                total_rate = kala["default_variant"]["statistics"]["total_rate"]
            except:
                total_rate = None
            #########################  link
            link = f"https://www.digikala.com/product/dkp-{id}/"
            
            #########################  count comment
            comment = session.get(f'https://api.digikala.com/v1/product/{id}/comments/')
            comment = json.loads(comment.text)
            numc    = comment["data"]["pager"]["total_items"]
            
            #########################  count question
            question = session.get(f'https://api.digikala.com/v1/product/{id}/questions/')
            question = json.loads(question.text)
            numq     = question["data"]["pager"]["total_items"]
            row = [id,name,all_star,star_rate,price,total_count,total_rate,numc,numq,link]
            write.writerow(row)

In [326]:
import pandas as pd 
columns = ["id","name","all_star","star_rate","price","total_count_feeling","total_rate_feeling","numc","numq","link"]

df = pd.read_csv("export.csv",names=columns)
df

,id,name,all_star,star_rate,price,total_count_feeling,total_rate_feeling,numc,numq,link
0,1792594,ماوس بی سیم تسکو مدل TM 667W,4341,4.1,2980000,77.0,86.2,3731,109,https://www.digikala.com/product/dkp-1792594/
1,1002387,ماوس بی سیم مدل 4D,6568,3.8,1000000,4.0,70.0,5703,200,https://www.digikala.com/product/dkp-1002387/
2,4580723,ماوس مخصوص بازی اونیکوما مدل CW905,705,4.6,4290000,5.0,100.0,989,213,https://www.digikala.com/product/dkp-4580723/
3,4250944,ماوس مدل A2RGB,722,4.3,2750000,19.0,83.2,696,57,https://www.digikala.com/product/dkp-4250944/
4,12143680,ماوس بی سیم بیاند مدل BM-171RF,71,4.1,2400000,69.0,82.4,72,8,https://www.digikala.com/product/dkp-12143680/
...,...,...,...,...,...,...,...,...,...,...
175,9572000,ماوس مدل M200,11,4.2,1350000,NaN,NaN,17,1,https://www.digikala.com/product/dkp-9572000/
176,13085607,ماوس بی سیم گرین لاین مدل GL-113,0,0.0,8050000,NaN,NaN,1,2,https://www.digikala.com/product/dkp-13085607/
177,323494,ماوس هترون مدل HM430,94,4.3,2150000,NaN,NaN,91,1,https://www.digikala.com/product/dkp-323494/
178,4064667,ماوس ای فورتک مدل N-70FXS,233,4.3,6400000,NaN,NaN,192,7,https://www.digikala.com/product/dkp-4064667/
179,7472434,ماوس بی سیم لاجیتک مدل M350,23,4.1,13300000,2.0,90.0,18,16,https://www.digikala.com/product/dkp-7472434/

In [ ]:
df.describe()

,id,all_star,star_rate,price,total_count_feeling,total_rate_feeling,numc,numq
count,1.800000e+02,180.000000,180.000000,1.800000e+02,136.000000,136.000000,180.000000,180.000000
mean,5.819786e+06,352.105556,4.152778,4.756078e+06,16.742647,84.667647,305.016667,19.455556
std,4.238311e+06,752.463897,0.483173,6.341266e+06,25.143734,13.394642,644.410618,39.069387
min,1.895000e+03,0.000000,0.000000,6.100000e+05,1.000000,20.000000,1.000000,0.000000
25%,1.734467e+06,20.750000,4.075000,1.835000e+06,3.000000,80.000000,20.000000,1.000000
50%,6.022358e+06,83.500000,4.200000,3.005000e+06,7.000000,86.300000,83.500000,5.000000
75%,9.352476e+06,383.000000,4.400000,5.550000e+06,19.000000,93.400000,302.000000,18.000000
max,1.365521e+07,6568.000000,4.900000,6.550000e+07,187.000000,100.000000,5703.000000,272.000000